version: '3.3'

services:

  nginx:
    image: nginx:1.15
    ports:
    - '6060:80'
    links:
        - otus
    volumes:
      - ./otus/www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  otus:
    build: ./otus
    ports:
      - '9000:9000'
    container_name: otus
    volumes:
      - ./otus/www:/var/www/html
